title: 林德熙
description: Windows 10 App Developer
author: lindexi
post_author: 林德熙
logo: /img/avatar.png
github: https://github.com/lindexi
about: Windows 10 App Developer
mail: "lindexi_gd@outlook.com"

baseurl: ""
url: "https://blog.lindexi.com"

allowsearch: false

analytics:
  google: UA-110214503-1
disqus:
  name: lindexi

share:
  twitter_username: lindexi_gd


enableTags: true
tagarray: []

excerpt_separator: "<!--more-->"
paginate: 35
per_page: 60
paginate_path: "/blog/page:num/"
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
   math_engine: mathjax
gems: [jekyll-paginate, jekyll-gist]

# Content Collection
collections:
  articles:
    output: true

# Content Template
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "林德熙"
      permalink: "/post/:title.html"
  - scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "post"
      author: "林德熙"
      permalink: "/article/:title.html"
